# Generated by Django 5.2.14 on 2026-05-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="national_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
