# Generated by Django 5.2.14 on 2026-06-14 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patient_national_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(max_length=11, verbose_name="شماره موبایل"),
                ),
                ("template", models.CharField(max_length=100, verbose_name="تمپلت")),
                (
                    "token",
                    models.CharField(
                        max_length=255, verbose_name="توکن ارسال\u200cشده"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "موفق"), ("failed", "ناموفق")],
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                ("response", models.TextField(blank=True, verbose_name="پاسخ سرویس")),
                ("error", models.TextField(blank=True, verbose_name="خطا")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ارسال"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_logs",
                        to="patients.patient",
                        verbose_name="بیمار",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ پیامک",
                "verbose_name_plural": "لاگ\u200cهای پیامک",
                "ordering": ("-created_at",),
            },
        ),
    ]
