# Generated by Django 5.2.14 on 2026-06-24 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_smsmessagelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visitor_id",
                    models.UUIDField(db_index=True, verbose_name="شناسه بازدیدکننده"),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="شناسه نشست",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "بازدید صفحه"),
                            ("form_view", "مشاهده فرم"),
                            ("form_submit_attempt", "تلاش ثبت\u200cنام"),
                            ("form_submit_success", "ثبت\u200cنام موفق"),
                            ("form_submit_invalid", "ثبت\u200cنام نامعتبر"),
                            ("form_submit_error", "خطای ثبت\u200cنام"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="نوع رویداد",
                    ),
                ),
                ("method", models.CharField(max_length=10, verbose_name="روش درخواست")),
                (
                    "path",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="مسیر"
                    ),
                ),
                ("query_string", models.TextField(blank=True, verbose_name="کوئری")),
                (
                    "referrer",
                    models.TextField(blank=True, verbose_name="ارجاع\u200cدهنده"),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="مرورگر/دستگاه"),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        verbose_name="هش آی\u200cپی",
                    ),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="وضعیت پاسخ"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="فراداده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان ایجاد"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit_events",
                        to="patients.patient",
                        verbose_name="بیمار",
                    ),
                ),
            ],
            options={
                "verbose_name": "رویداد بازدید",
                "verbose_name_plural": "رویدادهای بازدید",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="VisitReport",
            fields=[],
            options={
                "verbose_name": "گزارش بازدید سایت",
                "verbose_name_plural": "گزارش بازدید سایت",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("patients.visitevent",),
        ),
        migrations.AddIndex(
            model_name="visitevent",
            index=models.Index(
                fields=["created_at"], name="patients_vi_created_dcc2a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitevent",
            index=models.Index(
                fields=["event_type"], name="patients_vi_event_t_da597a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitevent",
            index=models.Index(
                fields=["visitor_id"], name="patients_vi_visitor_c01a4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitevent",
            index=models.Index(fields=["path"], name="patients_vi_path_959dc8_idx"),
        ),
    ]
