# Generated by Django 5.2.5 on 2026-07-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_done_sms_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'بازدید صفحه'), ('form_view', 'مشاهده فرم'), ('hero_cta_click', 'کلیک CTA اصلی'), ('sticky_cta_click', 'کلیک CTA چسبان'), ('section_view', 'مشاهده بخش صفحه'), ('form_start', 'شروع تکمیل فرم'), ('field_complete', 'تکمیل فیلد فرم'), ('scroll_depth', 'عمق اسکرول'), ('form_submit_attempt', 'تلاش ثبت\u200cنام'), ('form_submit_success', 'ثبت\u200cنام موفق'), ('form_submit_invalid', 'ثبت\u200cنام نامعتبر'), ('form_submit_error', 'خطای ثبت\u200cنام')], db_index=True, max_length=32, verbose_name='نوع رویداد'),
        ),
    ]
